// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var TodoApp$ReactTemplate = require("./TodoApp.bs.js");

Css.$$global("body, div", /* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.flexDirection(/* column */-963948842),
        /* :: */[
          Css.boxSizing(/* borderBox */9307263),
          /* :: */[
            Css.flexShrink(0),
            /* [] */0
          ]
        ]
      ]
    ]);

Css.$$global("body", /* :: */[
      Css.fontSize(Css.px(14)),
      /* :: */[
        Css.fontFamily("'Century Gothic', Futura, sans-serif"),
        /* [] */0
      ]
    ]);

Css.$$global("#root", /* :: */[
      Css.alignItems(Css.center),
      /* :: */[
        Css.justifyContent(Css.center),
        /* :: */[
          Css.position(Css.absolute),
          /* :: */[
            Css.top(Css.zero),
            /* :: */[
              Css.left(Css.zero),
              /* :: */[
                Css.bottom(Css.zero),
                /* :: */[
                  Css.right(Css.zero),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

Css.$$global("input[type='checkbox']", /* :: */[
      Css.marginRight(Css.px(10)),
      /* [] */0
    ]);

Css.$$global("input[type='text']", /* :: */[
      Css.alignSelf(Css.stretch),
      /* :: */[
        Css.padding2(Css.px(3), Css.px(5)),
        /* :: */[
          Css.marginTop(Css.px(20)),
          /* [] */0
        ]
      ]
    ]);

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, TodoApp$ReactTemplate.make(/* array */[])), "root");

/*  Not a pure module */
