// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("TodoApp");

var app = Css.style(/* :: */[
      Css.width(Css.px(280)),
      /* :: */[
        Css.maxHeight(Css.px(600)),
        /* :: */[
          Css.flex(1),
          /* :: */[
            Css.boxShadow(Css.zero, Css.px(2), Css.px(15), undefined, undefined, Css.hex("ccc")),
            /* :: */[
              Css.margin(Css.px(10)),
              /* :: */[
                Css.alignItems(Css.stretch),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var title = Css.style(/* :: */[
      Css.fontSize(Css.px(20)),
      /* :: */[
        Css.alignItems(Css.center),
        /* :: */[
          Css.padding(Css.px(20)),
          /* [] */0
        ]
      ]
    ]);

var items = Css.style(/* :: */[
      Css.margin2(Css.px(10), Css.zero),
      /* :: */[
        Css.textAlign(Css.center),
        /* :: */[
          Css.flex(1),
          /* :: */[
            Css.overflow(Css.auto),
            /* [] */0
          ]
        ]
      ]
    ]);

var footer = Css.style(/* :: */[
      Css.alignItems(Css.flexStart),
      /* :: */[
        Css.padding2(Css.px(5), Css.px(10)),
        /* [] */0
      ]
    ]);

var item = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.padding2(Css.px(10), Css.px(20)),
        /* :: */[
          Css.alignItems(Css.center),
          /* :: */[
            Css.flexDirection(Css.row),
            /* [] */0
          ]
        ]
      ]
    ]);

var checkbox = Css.style(/* :: */[
      Css.marginRight(Css.px(20)),
      /* [] */0
    ]);

var Styles = /* module */[
  /* app */app,
  /* title */title,
  /* items */items,
  /* footer */footer,
  /* item */item,
  /* checkbox */checkbox
];

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: app
                        }, React.createElement("div", {
                              className: title
                            }, "What to do"), React.createElement("div", {
                              className: items
                            }, "Nothing"));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.Styles = Styles;
exports.make = make;
/* component Not a pure module */
